
INSERT INTO nouns(word) VALUES
  ('cloud'),
  ('elephant'),
  ('go language'),
  ('laptop'),
  ('container'),
  ('micro-service'),
  ('turtle'),
  ('whale'),
  ('gopher'),
  ('moby dock'),
  ('server'),
  ('bicycle'),
  ('viking'),
  ('mermaid'),
  ('fjord'),
  ('lego'),
  ('flodebolle'),
  ('smorrebrod');

INSERT INTO verbs(word) VALUES
  ('will drink'),
  ('smashes'),
  ('smokes'),
  ('eats'),
  ('walks towards'),
  ('loves'),
  ('helps'),
  ('pushes'),
  ('debugs'),
  ('invites'),
  ('hides'),
  ('will ship');

INSERT INTO adjectives(word) VALUES
  ('the exquisite'),
  ('a pink'),
  ('the rotten'),
  ('a red'),
  ('the serverless'),
  ('a broken'),
  ('a shiny'),
  ('the pretty'),
  ('the impressive'),
  ('an awesome'),
  ('the famous'),
  ('a gigantic'),
  ('the glorious'),
  ('the nordic'),
  ('the welcoming'),
  ('the delicious');
